config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('api/',include('core.api.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/api/urls.py
from  django.urls import  path
from .views import  getRoutes, getRooms, getRoom


urlpatterns = [
    path('' ,getRoutes ),
    path('rooms/', getRooms), 
    path('rooms/<int:pk>/', getRoom),
]

core/urls.py
from django.urls import path

from .views import ActivityPage,TopicPage,home,room,CreateView,UpdateView, UpdateUser,DeleteView,LoginPage,LogoutPage,RegisterPage,Deletemessage,Profile
app_name='core'

urlpatterns = [
    path('login/',LoginPage,name='login'),
    path('logout/',LogoutPage,name='logout'),
    path('register/',RegisterPage,name='register'),
    path('', home, name='home'),
    path('profile/<int:pk>/',Profile,name='profile'),
    path('room/<int:pk>/',room,name='room'),
    path('create-room/',CreateView,name='create-room'),
    path('update-room/<int:pk>/',UpdateView,name='update-room'),
    path('delete-room/<int:pk>/',DeleteView,name='delete-room'),
    path('delete-message/<int:pk>/',Deletemessage,name='delete-message'),
    path('update-user/',UpdateUser,name='update-user'),
    path('topics/',TopicPage,name='topics'),
    path('activity/',ActivityPage,name='activity'),
]

core/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    name=models.CharField(max_length=100 , blank=True, null=True)
    email=models.EmailField(max_length=100 , unique=True,blank=True, null=True)
    bio=models.TextField(max_length=100 , blank=True, null=True)
    avatar=models.ImageField(default="avatar.svg", blank=True, null=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

class Topic(models.Model):
    name = models.CharField(max_length=200,null=True,blank=True)
    def __str__(self):
        return self.name

class Room(models.Model):
    host=models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True)
    topic=models.ForeignKey(Topic,on_delete=models.SET_NULL,null=True)
    name = models.CharField(max_length=255,null=True,blank=True)
    description = models.TextField(max_length=1000,null=True,blank=True)
    participants = models.ManyToManyField(User,related_name='participants',blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created' , '-updated']

    def __str__(self):
        return self.name



class Message(models.Model):
    room = models.ForeignKey(Room,on_delete=models.CASCADE,null=True,blank=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True)
    content = models.TextField(max_length=1000,null=True,blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    class Meta:
        ordering = ['-created' , '-updated']

    def __str__(self):
        return self.content[:50]

core/forms.py
from django.forms import ModelForm
from .models import *
from django.contrib.auth.forms import UserCreationForm



class MyUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
class RoomForm(ModelForm):
    class Meta:
        model = Room
        fields = '__all__'
        exclude = ['participants', 'host']


class Userform(ModelForm):
    class Meta:
        model = User
        fields = ['name','bio','avatar','username', 'email']

core/api/views.py
from django.http import JsonResponse
from rest_framework.decorators import  api_view
from rest_framework.response import  Response
from core.models import Room
from .serialaizers import RoomSerializer

@api_view(['GET'])
def getRoutes(request):
    routes = [
        'GET /api/', 
        'GET /api/rooms/',
        'GET /api/rooms/:id',
    ]
    return Response(routes)
@api_view(['GET'])
def getRooms(request):
    rooms = Room.objects.all()
    serializer = RoomSerializer(rooms, many=True)
    return Response(serializer.data)

@api_view(['GET'])
def getRoom(request,pk):
    room = Room.objects.get(id=pk)
    serializer = RoomSerializer(room, many=False)
    return Response(serializer.data)

core/views.py
from django.shortcuts import render,redirect
from .models import Room,Message,Topic,User
from .forms import RoomForm,Userform,MyUserCreationForm
from django.db.models import Q
from django.contrib import messages
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
# Create your views here.


def LoginPage(request):
    page='login'
    if request.user.is_authenticated:
        return redirect('core:home')    
    if request.method=='POST':
        email=request.POST.get('email').lower()
        password=request.POST.get('password')
        try:
            user=User.objects.get(email=email)
        except:
            messages.error(request,'Email is not found')
        user=authenticate(request, email=email,password=password)

        if user is not None:
            login(request,user)
            return redirect('core:home')
        else:
            messages.error(request,'Invalid username or password')

    context={
        'page':page,
    }
    return render(request,'core/login_register.html',context)

def LogoutPage(request):
    logout(request)
    return redirect('core:home')

def RegisterPage(request):
    page='register'
    form=MyUserCreationForm()
    if request.method=='POST':
        form=MyUserCreationForm(request.POST)
        if form.is_valid():
            user=form.save(commit=False)
            user.username=user.username.lower()
            user.save()
            login(request,user)
            return redirect('core:home')
        else:
            messages.error(request,'an error Occoured during registration')
    context={
        'form':form,
    }
    return render(request,'core/login_register.html',context)

def home(request):
    q=request.GET.get('q') if request.GET.get('q') else ''
    rooms=Room.objects.filter(
        Q(topic__name__icontains=q) |
        Q(name__icontains=q) |
        Q(description__icontains=q)
    
    ) 
    topics=Topic.objects.all()[0:5]
    room_count=rooms.count()
    room_message=Message.objects.filter(Q(room__topic__name__icontains=q)) 
    context={
        'rooms':rooms,
        'topics':topics,
        'room_count':room_count,
        'room_message':room_message,
    }
    return render(request,'core/home.html',context)

def room(request,pk):
   
    room=Room.objects.get(id=pk)
    room_message=room.message_set.all()
    participants=room.participants.all()
    if request.method=='POST':
        message=Message.objects.create(
            user=request.user,
            room=room,
            content=request.POST.get('body')
        )
        room.participants.add(request.user)
        return redirect('core:room',pk=room.id)
    context={
        'room':room,
        'room_message':room_message,
        'participants':participants,
                   
    }

    return render(request, 'core/room.html',context)

def Profile(request , pk):
    user=User.objects.get(id=pk)
    rooms=user.room_set.all()
    room_message=user.message_set.all()
    topics=Topic.objects.all()
    context={
        'user':user,
        'rooms':rooms,
        'room_message':room_message,
        'topics':topics,
    }
    return render(request,'core/profile.html', context)
#CRUD
@login_required(login_url='core:login')
def CreateView(request):
    form=RoomForm()
    topics=Topic.objects.all()
    if request.method=='POST':
        topic_name=request.POST.get('topic')
        topic,created=Topic.objects.get_or_create(name=topic_name)
        Room.objects.create(
            host=request.user,
            topic=topic,
            name=request.POST.get('name'),
            description=request.POST.get('description'),
        )
        return redirect('core:home')
    context={
        'form':form,
        'topics':topics,
    }
    return render(request,'core/room_form.html',context)

@login_required(login_url='core:login')
def UpdateView(request,pk):
    room=Room.objects.get(id=pk)
    form=RoomForm(instance=room)
    topics=Topic.objects.all()
    if request.user != room.host:
        return HttpResponse('You are not allowed to update this room')
    if request.method=='POST':
        topic_name=request.POST.get('topic')
        topic,created=Topic.objects.get_or_create(name=topic_name)
        room.topic=topic
        room.name=request.POST.get('name')
        room.description=request.POST.get('description')
        room.save()
        return redirect('core:home')
    context={
        'form':form,
        'topics':topics,
        'room':room,
    }
    return render(request,'core/room_form.html',context)
@login_required(login_url='core:login')
def DeleteView(request,pk):
    room=Room.objects.get(id=pk)
    if request.user != room.host:
        return HttpResponse('You are not allowed to delete this room')
    if request.method=='POST':
        room.delete()
        return redirect('core:home')
    context={
        'room':room
    }
    return render(request,'core/delete.html',context)

@login_required(login_url='core:login')
def Deletemessage(request,pk):
    message=Message.objects.get(id=pk)
    if request.user != message.host:
        return HttpResponse('You are not allowed to delete this room')
    if request.method=='POST':
        message.delete()
        return redirect('core:home')
    context={
        'message':message
    }
    return render(request,'core/delete.html',context)

@login_required(login_url='core:login')
def UpdateUser(request):
    user=request.user
    form=Userform(instance=user)
    if request.method=='POST':
        form=Userform(request.POST,request.FILES,instance=user)
        if form.is_valid():
            form.save()
            return redirect('core:profile',pk=user.id)
    context={
        'form':form,
    }
    return render(request,'core/update-user.html',context)

def TopicPage(request):
    q=request.GET.get('q') if request.GET.get('q') else ''
    topics=Topic.objects.filter(name__icontains=q)
    context={
        'topics':topics,
    }

    return render(request,'core/topics.html',context)

def ActivityPage(request):
    room_messages=Message.objects.all()
    context={
        'room_messages':room_messages,
    }
    return render(request,'core/activity.html',context)

core/templates/core/activity.html
<div class="activities">
    <div class="activities__header">
      <h2>Recent Activities</h2>
    </div>
    {% for message in room_message %}
    <div class="activities__box">
      <div class="activities__boxHeader roomListRoom__header">
        <a href="{% url 'core:profile' message.user.id %}" class="roomListRoom__author">
          <div class="avatar avatar--small">
            <img src="{{message.user.avatar.url}}" />
          </div>
          <p>
            @{{message.user}}
            <span>{{message.created|timesince}} ago</span>
          </p>
        </a>
        {%  if request.user == massage.user %}
        <div class="roomListRoom__actions">
          <a href="{% url  'core:delete-massage' message.id %}  ">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>remove</title>
              <path
                d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
              ></path>
            </svg>
          </a>
        </div>
        {% endif %} 
      </div>
      <div class="activities__boxContent">
        <p>replied to post “<a href="{% url 'core:room' message.room.id %}">{{message.room}}</a>”</p>
        <div class="activities__boxRoomContent">
            <p>{{message.content}}</p>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>    

core/templates/core/delete.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" href="assets/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" href="style.css" />
    <title>StudyBuddy - Find study partners around the world!</title>
</head>

<body>
    <header class="header header--loggedIn">
        <div class="container">
            <a href="/" class="header__logo">
                <img src="assets/logo.svg" />
                <h1>StudyBuddy</h1>
            </a>
            <form class="header__search">
                <label>
                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                        <title>search</title>
                        <path
                            d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z">
                        </path>
                    </svg>
                    <input placeholder="Search for posts" />
                </label>
            </form>
            <nav class="header__menu">
                <!-- Not Logged In -->
                <!-- <a href="/login.html">
            <img src="./assets/avatar.svg" />
            <p>Account</p>
          </a> -->

                <!-- Logged In -->
                <a href="#">
                    <div class="avatar avatar--medium active">
                        <img src="https://randomuser.me/api/portraits/men/37.jpg" />
                    </div>
                    <p>John Doe <span>@john_doe</span></p>
                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                        <title>chevron-down</title>
                        <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
                    </svg>
                </a>
            </nav>
        </div>
    </header>
    <main class="delete-item layout">
        <div class="container">
            <div class="layout__box">
                <div class="layout__boxHeader">
                    <div class="layout__boxTitle">
                        <a href="index.html">
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                viewBox="0 0 32 32">
                                <title>arrow-left</title>
                                <path
                                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                                </path>
                            </svg>
                        </a>
                        <h3>Back</h3>
                    </div>
                </div>
                <div class="layout__body">
                    <form class="form" action="#">
                        <div class="form__group">
                            <p>Are you sure you want to delete "100 days of code"?</p>
                        </div>

                        <div class="for__group">
                            <input class="btn btn--main" type="submit" value="Confirm" />
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </main>
    <script src="script.js"></script>
</body>

</html>

core/templates/core/home.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
    <main class="layout layout--3">
      <div class="container">
        <!-- Topics Start -->
           {% include 'core/topic.html' %}
        <!-- Topics End -->

        <!-- Room List Start -->
        <div class="roomList">
          <div class="mobile-menu">
            <form class="header__search" method="GET" action="{% url 'core:home'   %}">
              <label>
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>search</title>
                  <path
                    d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
                  ></path>
                </svg>
                <input name="q" placeholder="Search for posts" />
              </label>
            </form>
            <div class="mobile-menuItems">
              <a class="btn btn--main btn--pill" href="{%  url 'core:topics' %}">Browse Topics</a>
              <a class="btn btn--main btn--pill" href="{% url 'core:activity' %}">Recent Activities</a>
            </div>
          </div>
          <div class="roomList__header">
            <div>
              <h2>Study Room</h2>
              <p>{{ rooms.count}}  Rooms available</p>
            </div>
            <a class="btn btn--main" href="{% url 'core:create-room' %}">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>add</title>
                <path
                  d="M16.943 0.943h-1.885v14.115h-14.115v1.885h14.115v14.115h1.885v-14.115h14.115v-1.885h-14.115v-14.115z"
                ></path>
              </svg>
              Create Room
            </a>
          </div>

          {% include 'core/feed.html' %}
        </div>
        <!-- Activities Start -->
        {% include 'core/activity.html' %}
        <!-- Activities End -->
      </div>
    </main>
{% endblock %}

core/templates/core/kiash.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Kiash Web api</h1>
    <div  id="room-container" ></div>
    <script>
        let roomContainer=document.getElementById("room-container");
        let getRooms = async () =>{
            let response = await fetch('http://127.0.0.1:8000/api/rooms/')
            let rooms= await response.json()
            for(let i=0; rooms.length > i; i++){
                let room=rooms[i]
                let row=`<div>
                    <h3>${room.name}</h3>
                </div>`
                roomContainer.innerHTML += row
            }
        }
        getRooms()
    </script>
</body>
</html>

core/templates/core/login_register.html
{% extends 'base.html' %}


{% load static %}

{% block content %}
    <main class="auth layout">
      {% if page == 'login' %}
        <div class="container">
          <div class="layout__box">
            <div class="layout__boxHeader">
              <div class="layout__boxTitle">
                <h3>Login</h3>
              </div>
            </div>
            <div class="layout__body">
              <h2 class="auth__tagline">Find your study partner</h2>

              <form class="form" action="" method="POST">
                {% csrf_token %}
                <div class="form__group form__group">
                  <label for="room_name">Email:</label>
                  <input id="username" name="email" type="text" placeholder="e.g. Kiash Kiash" />
                </div>
                <div class="form__group">
                  <label for="password">Password</label>
                  <input
                    id="password"
                    name="password"
                    type="password"
                    placeholder="&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;"
                  />
                </div>

                <button class="btn btn--main" type="submit">
                  <svg
                    version="1.1"
                    xmlns="http://www.w3.org/2000/svg"
                    width="32"
                    height="32"
                    viewBox="0 0 32 32"
                  >
                    <title>lock</title>
                    <path
                      d="M27 12h-1v-2c0-5.514-4.486-10-10-10s-10 4.486-10 10v2h-1c-0.553 0-1 0.447-1 1v18c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-18c0-0.553-0.447-1-1-1zM8 10c0-4.411 3.589-8 8-8s8 3.589 8 8v2h-16v-2zM26 30h-20v-16h20v16z"
                    ></path>
                    <path
                      d="M15 21.694v4.306h2v-4.306c0.587-0.348 1-0.961 1-1.694 0-1.105-0.895-2-2-2s-2 0.895-2 2c0 0.732 0.413 1.345 1 1.694z"
                    ></path>
                  </svg>

                  Login
                </button>
              </form>

              <div class="auth__action">
                <p>Haven't signed up yet?</p>
                <a href="{% url 'core:register' %}" class="btn btn--link">Sign Up</a>
              </div>
            </div>
          </div>
        </div>
      {% else %}
      <div class="container">
        <div class="layout__box">
          <div class="layout__boxHeader">
            <div class="layout__boxTitle">
              <h3>Register</h3>
            </div>
          </div>
          <div class="layout__body">
            <h2 class="auth__tagline">Find your study partner</h2>

            <form class="form" action="" method="POST">
              {% csrf_token %}
              {% for field in form %}
              <div class="form__group form__group">
                <label for="room_name">{{field.label}}</label>
                {{field }}
              </div>
              {% endfor %}
             

              <button class="btn btn--main" type="submit">
                <svg
                  version="1.1"
                  xmlns="http://www.w3.org/2000/svg"
                  width="32"
                  height="32"
                  viewBox="0 0 32 32"
                >
                  <title>lock</title>
                  <path
                    d="M27 12h-1v-2c0-5.514-4.486-10-10-10s-10 4.486-10 10v2h-1c-0.553 0-1 0.447-1 1v18c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-18c0-0.553-0.447-1-1-1zM8 10c0-4.411 3.589-8 8-8s8 3.589 8 8v2h-16v-2zM26 30h-20v-16h20v16z"
                  ></path>
                  <path
                    d="M15 21.694v4.306h2v-4.306c0.587-0.348 1-0.961 1-1.694 0-1.105-0.895-2-2-2s-2 0.895-2 2c0 0.732 0.413 1.345 1 1.694z"
                  ></path>
                </svg>

                Register
              </button>
            </form>

            <div class="auth__action">
              <p>already have an account signed up yet?</p>
              <a href="{%  url 'core:login' %}" class="btn btn--link">Sign Up</a>
            </div>
          </div>
        </div>
      </div>
      {% endif %}
    </main>
{% endblock %}

core/templates/core/profile.html
{% extends 'base.html' %}

{% load static %}

{%   block content %}

  <main class="profile-page layout layout--3">
    <div class="container">
      <!-- Topics Start -->
      {% include 'core/topic.html' %}
      <!-- Topics End -->

      <!-- Room List Start -->
      <div class="roomList">
        <div class="profile">
          <div class="profile__avatar">
            <div class="avatar avatar--large active">
              <img src="{{user.avatar.url}}" />
            </div>
          </div>
          <div class="profile__info">
            <h3>{{user.username}}</h3>
            <p>@{{user.username}}</p>
            {% if request.user == user %}
            <a href="{%  url 'core:update-user' %}" class="btn btn--main btn--pill">Edit Profile</a>
            {% endif %}
          </div>
          <div class="profile__about">
            <h3>About</h3>
            <p>{{user.bio}}</p>
          </div>
        </div>

        <div class="roomList__header">
          <div>
            <h2>Study Rooms Hosted by dennis_ivy</a>
            </h2>
          </div>
        </div>
        {% include 'core/feed.html' %}
      </div>
      <!-- Room List End -->

      <!-- Activities Start -->
      {% include 'core/activity.html' %}
      <!-- Activities End -->
    </div>
  </main>

    {% endblock %}

core/templates/core/room.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <main class="profile-page layout layout--2">
      <div class="container">
        <!-- Room Start -->
        <div class="room">
          <div class="room__top">
            <div class="room__topLeft">
              <a href="{% url 'core:home' %}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>arrow-left</title>
                  <path
                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
                  ></path>
                </svg>
              </a>
              <h3>Study Room</h3>
            </div>
            {% if room.host == request.user %}
            <div class="room__topRight">
              <a href="{% url 'core:update-room' room.id %}">
                <svg
                  enable-background="new 0 0 24 24"
                  height="32"
                  viewBox="0 0 24 24"
                  width="32"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <title>edit</title>
                  <g>
                    <path d="m23.5 22h-15c-.276 0-.5-.224-.5-.5s.224-.5.5-.5h15c.276 0 .5.224.5.5s-.224.5-.5.5z" />
                  </g>
                  <g>
                    <g>
                      <path
                        d="m2.5 22c-.131 0-.259-.052-.354-.146-.123-.123-.173-.3-.133-.468l1.09-4.625c.021-.09.067-.173.133-.239l14.143-14.143c.565-.566 1.554-.566 2.121 0l2.121 2.121c.283.283.439.66.439 1.061s-.156.778-.439 1.061l-14.142 14.141c-.065.066-.148.112-.239.133l-4.625 1.09c-.038.01-.077.014-.115.014zm1.544-4.873-.872 3.7 3.7-.872 14.042-14.041c.095-.095.146-.22.146-.354 0-.133-.052-.259-.146-.354l-2.121-2.121c-.19-.189-.518-.189-.707 0zm3.081 3.283h.01z"
                      />
                    </g>
                    <g>
                      <path
                        d="m17.889 10.146c-.128 0-.256-.049-.354-.146l-3.535-3.536c-.195-.195-.195-.512 0-.707s.512-.195.707 0l3.536 3.536c.195.195.195.512 0 .707-.098.098-.226.146-.354.146z"
                      />
                    </g>
                  </g>
                </svg>
              </a>
              <a href="{% url 'core:delete-room' room.id %}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>remove</title>
                  <path
                    d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                  ></path>
                </svg>
              </a>
            </div>
            {% endif %}
  
          </div>
          <div class="room__box scroll">
            <div class="room__header scroll">
              <div class="room__info">
                <h3>{{room.name}}</h3>
                <span>{{room.created|timesince}} ago</span>
              </div>
              <div class="room__hosted">
                <p>Hosted By</p>
                <a href="{% url 'core:profile' room.host.id %}" class="room__author">
                  <div class="avatar avatar--small">
                    <img src="{{room.host.avatar.url}}" />
                  </div>
                  <span>@{{room.host.username}}</span>
                </a>
              </div>

              <span class="room__topics">{{room.topic}}</span>
            </div>
            <div class="room__conversation">
              <div class="threads scroll">
                {% for message in room_message %}
                <div class="thread">
                  <div class="thread__top">
                    <div class="thread__author">
                      <a href="{% url 'core:profile' message.user.id %}" class="thread__authorInfo">
                        <div class="avatar avatar--small">
                          <img src="{{room.host.avatar.url}}" />
                        </div>
                        <span>@{{message.user.username}}</span>
                      </a>
                      <span class="thread__date">{{message.created|timesince}} ago</span>
                    </div>
                    {% if request.user == message.user %}
                    <a href="{% url 'core:delete-message' message.id  %}">
                    <div class="thread__delete">
                      <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                        <title>remove</title>
                        <path
                          d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                        ></path>
                      </svg>
                    </div>
                   </a>
                    {% endif %}
                  </div>
                  <div class="thread__details">
                   {{message.content}}
                  </div>
                </div>
                {% endfor %}
              </div>
            </div>
          </div>
          <div class="room__message">
            <form action=""  method="POST">
              {% csrf_token %}
              <input name="body" placeholder="Write your message here..." /></form>
          </div>
        </div>
        <!-- Room End -->

        <!--   Start -->
        <div class="participants">
          <h3 class="participants__top">Participants <span>({{participants.count}})</span></h3>
          <div class="participants__list scroll">
            {% for user in participants %}
            <a href="{% url 'core:profile' user.id %}" class="participant">
              <div class="avatar avatar--medium">
                <img src="{{room.host.avatar.url}}" />
              </div>
              <p>
                {{user.username}}
                <span>@{{user.username}}</span>
              </p>
            </a>
            {% endfor  %}
          </div>
        </div>
        <!--  End -->
      </div>
    </main>
    <script src="{% static 'script.js' %}"></script>
  {% endblock %}

core/templates/core/topic.html
<div class="topics">
    <div class="topics__header">
      <h2>Browse Topics</h2>
    </div>
    <ul class="topics__list">
      <li>
        <a href="{% url 'core:home' %}" class="active">All<span>{{topics.count}}</span></a>
      </li>
      {% for topic in topics %}
      <li>
        <a href="{% url 'core:home' %}?q={{topic.name}}">{{topic.name}} <span>{{topic.room_set.all.count}}</span></a>
      </li>
      {% endfor %} 
    </ul>
    <a class="btn btn--link" href="{% url 'core:topics' %}">
      More
      <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
        <title>chevron-down</title>
        <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
      </svg>
    </a>
  </div> 